name: Deploy presentation
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install & build slides
        run: |
          cd slides
          npm install
          npm install @slidev/cli @slidev/theme-default
          npx slidev build --base mongodb-spring-kurs-dla-poczatkujacych
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: slides/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}